[tool.poetry]
name = "depmap-biocypher"
version = "0.1.0"
description = "DepMap BioCypher adapter"
authors = ["Sebastian Lobentanzer <sebastian.lobentanzer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
biocypher = {path = "../BioCypher"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
