biocypher:
  offline: true
  strict_mode: true
  dbms: neo4j
  schema_config_path: config/schema_config.yaml

neo4j:
  database_name: neo4j
  quote_character: '"'
  skip_duplicate_nodes: true
  skip_bad_relationships: true